model = "gpt-5.1-codex-mini"

model_verbosity = "high"
web_search_request = true

project_doc_fallback_filenames = ["CLAUDE.md"]

notify = ["ntfy", "publish", "--quiet", "--title", "Codex"] 

[sandbox_workspace_write]
network_access = true
